# Generated by Django 3.2.25 on 2024-04-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.CharField(default='Word Search', max_length=50)),
                ('time', models.TimeField()),
                ('tries', models.IntegerField()),
            ],
        ),
    ]
