# Generated by Django 3.2.25 on 2024-04-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_core', '0003_badge_playerbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image_url',
        ),
        migrations.AddField(
            model_name='badge',
            name='image_svg',
            field=models.TextField(default='URL_POR_DEFECTO'),
        ),
        migrations.AddField(
            model_name='badge',
            name='min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbadge',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_badges', to='match_core.season'),
        ),
    ]
